### PR TITLE
resource/pagerduty_user_contact_method: Add support for push_notification_contact_method

### LINKED ISSUE #86: Add support for push_notification_contact_method type in pagerduty_user_contact_method resource
### Versions

Terraform: v0.11.7
Pagerduty: v1.1.0

### Affected Resource(s)

- pagerduty_user_contact_method

### Terraform Configuration Files

```hcl
provider "pagerduty" {}

resource "pagerduty_user" "example" {
  color       = "green"
  description = ""
  email       = "example@example.com"
  job_title   = "Example"
  name        = "example"
  role        = "user"
}

resource "pagerduty_user_contact_method" "example" {
  address = "<LONG_NOTIFICATION_ID>"
  label   = "Label"
  type    = "push_notification_contact_method"
  user_id = "${pagerduty_user.example.id}"
}
```

### Expected Behavior

`terraform plan` and `terraform apply` complete successfully.

### Actual Behavior

`terraform plan` and `terraform apply` fail with errors like this:
```
Error: pagerduty_user_contact_method.example: "push_notification_contact_method" is an invalid value for argument type. Must be one of []string{"email_contact_method", "phone_contact_method", "sms_contact_method"}
```

### Steps to Reproduce

1. Copy example configuration provided above;
2. Run `terraform plan` or `terraform apply` and see error mentioned in [Actual Behavior](#actual-behavior) section.

### PR DESCRIPTION
**Pull request by heimweh**
Fixes #86 by adding push_notification_contact_method to the list of available types.

API reference: https://v2.developer.pagerduty.com/v2/page/api-reference#!/Users/post_users_id_contact_methods

### CODE REVIEW

File: pagerduty/resource_pagerduty_user_contact_method.go [hunk 1]
```diff
@@ -30,6 +30,7 @@ func resourcePagerDutyUserContactMethod() *schema.Resource {
 				ValidateFunc: validateValueFunc([]string{
 					"email_contact_method",
 					"phone_contact_method",
+					"push_notification_contact_method",
```
Comment (tombuildsstuff) [inline pagerduty/resource_pagerduty_user_contact_method.go]: does this also need to be added to the docs?

Comment (heimweh) [reply pagerduty/resource_pagerduty_user_contact_method.go]: Documentation should be up-to-date now :)
