### PR TITLE
data-source/pagerduty_extension_schema: Query specific extension schemas using query param

### LINKED ISSUE #77: Unable to locate extension schema
### Terraform Version
Terraform v0.10.7
Pagerduty Provider v1.0.0

### Affected Resource(s)
- pagerduty_extension_schema

### Terraform Configuration Files
```hcl
data "pagerduty_extension_schema" "slack" {
  name = "Slack"
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior
Terraform should have created a `pagerduty_extension` resource using the schema

### Actual Behavior
Terraform output an error
```
Error refreshing state: 1 error(s) occurred:

* data.pagerduty_extension_schema.slack: 1 error(s) occurred:

* data.pagerduty_extension_schema.slack: data.pagerduty_extension_schema.slack: Unable to locate any extension schema with the name: Slack
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create pagerduty_extension_schema object like
```
data "pagerduty_extension_schema" "slack" {
  name = "Slack"
}
```
2. Create a `pagerduty_extension` resource which references the `pagerduty_extension_schema`
3. `terraform plan`

### Important Factoids
This was working a few days ago. Haven't made any changes to our codebase

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

### PR DESCRIPTION
**Pull request by heimweh**
This change adds support for querying specific extension schemas by using a `query` param in the list call. 

This fixes #77 and the following failing test:

Before:

```
terraform-provider-pagerduty |> make testacc TEST=./pagerduty TESTARGS='-run=TestAccDataSourcePagerDutyExtensionSchema_Basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./pagerduty -v -run=TestAccDataSourcePagerDutyExtensionSchema_Basic -timeout 120m
=== RUN   TestAccDataSourcePagerDutyExtensionSchema_Basic
--- FAIL: TestAccDataSourcePagerDutyExtensionSchema_Basic (1.49s)
        testing.go:459: Step 0 error: Error refreshing: 1 error(s) occurred:

                * data.pagerduty_extension_schema.foo: 1 error(s) occurred:

                * data.pagerduty_extension_schema.foo: data.pagerduty_extension_schema.foo: Unable to locate any extension schema with the name: slack
FAIL
FAIL    github.com/terraform-providers/terraform-provider-pagerduty/pagerduty   1.494s
make: *** [GNUmakefile:17: testacc] Error 1
```

After:

```
terraform-provider-pagerduty |> make testacc TEST=./pagerduty TESTARGS='-run=TestAccDataSourcePagerDutyExtensionSchema_Basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./pagerduty -v -run=TestAccDataSourcePagerDutyExtensionSchema_Basic -timeout 120m
=== RUN   TestAccDataSourcePagerDutyExtensionSchema_Basic
--- PASS: TestAccDataSourcePagerDutyExtensionSchema_Basic (4.56s)
PASS
ok      github.com/terraform-providers/terraform-provider-pagerduty/pagerduty   4.572s
```

### CODE REVIEW

**Comment by pdecat** [comment]
Awesome!

File: pagerduty/data_source_pagerduty_extension_schema.go [hunk 1]
```diff
@@ -33,7 +33,7 @@ func dataSourcePagerDutyExtensionSchemaRead(d *schema.ResourceData, meta interfa
 
 	searchName := d.Get("name").(string)
 
-	resp, _, err := client.ExtensionSchemas.List()
+	resp, _, err := client.ExtensionSchemas.List(&pagerduty.ListExtensionSchemasOptions{Query: searchName})
```
Comment (paultyng) [inline pagerduty/data_source_pagerduty_extension_schema.go]: Does the regex match on label functionality no longer get used if this query is explicit? If so, should probably be removed.

Comment (heimweh) [reply pagerduty/data_source_pagerduty_extension_schema.go]: I totally agree, we should actually be able to drop the regex matching altogether.

One idea would be to replace the current regex matching with something like this:

```go
    var found *pagerduty.ExtensionSchema

    for _, es := range resp.ExtensionSchemas {
        if strings.EqualFold(es.Label, searchName) {
            found = es
        }
    }

    if found == nil {
        return fmt.Errorf("Unable to locate any extension schema with the name: %s", searchName)
    }
```

to _still_ allow case-insensitive matching (such as **slack**/**Slack**).

What do you think?

Comment (pdecat) [reply pagerduty/data_source_pagerduty_extension_schema.go]: Shouldn't this datasource ensure that there is exactly one match?

That, or return a list, with the benefit of returning an empty list instead of erroring when no match is found.

Comment (paultyng) [reply pagerduty/data_source_pagerduty_extension_schema.go]: Typically the pattern we use is have a separate data source (with a plural name) when you want to return a list, and have the singular data source error if multiple matches are found.

That being said, I think EqualFold would be great (didn't even know that function existed until now!) as long as Pager Duty is also case insensitive when we use the Query? If thats the case though, I'd say go ahead and make that change.

Comment (heimweh) [reply pagerduty/data_source_pagerduty_extension_schema.go]: That sounds good to me :+1:

PagerDuty does indeed seem to be case insensitive, 
so I'll go ahead and submit the change with `EqualFold`.

Thank you both so much for helping me out on this one :pray:

**Comment by EthanBlackburn** [comment]
This is awesome. Can this get landed?

**Comment by anthonyhobbs-jet** [comment]
Would love to see this merged in, as I think this is the bug blocking my adoption of Terraform for PagerDuty.

**Comment by bcornils** [comment]
@paultyng are we good to merge or do we need to do something else on our end? It appears everything is passing. I wasn't sure if we needed to wait for a release? Or we do weeklies.

**Comment by paultyng** [comment]
Added some minor fixes, I'm noticing some acc tests no longer pass (but not ones associated with this). Will have to dig in to those later.
